### PR TITLE
Fix: fixing bugs on expertise section

### PR DESCRIPTION
**Pull request by ishoborabyose**
###  PR DESCRIPTION

- This PR Fix bugs in the Expertise section

### TASKS COMPLETED

- [x] Created a new folder called data collection
- [x] Created a new file called data into data collection folder
- [x] Insert expertise section data into a data file
- [x] Insert and update expertise section component

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout fix/expertise-section
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard to understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#032: https://www.notion.so/apeunit/Fixing-Expertise-section-c3f7af0f56cd4a6d8fd8cfa843f89585

### CODE REVIEW

**Review by arjorb — APPROVED** [review]
Hey @ishoborabyose, you did a great job... it looks good to me!

**Review by haroldmud — CHANGES_REQUESTED** [review]
Your website looks nice even though there are still some tiny changes you need to work on

image
 Decrease the gap between the heading and the items on the mobile device. for it to look like this:
image

**Review by Nkaka23dev — APPROVED** [review]
Great Job!

**Comment by ishoborabyose** [comment]
> Your website looks nice even though there are still some tiny changes you need to work on
> 
> image Decrease the gap between the heading and the items on the mobile device. for it to look like this: image

**Review by haroldmud — APPROVED** [review]

**Pull request merged**
